POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email": "tisuOk@mail.com",
    "password": "testpassword"
}
###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email": "tisuOk@mail.com",
    "password": "testpassword"
}

###
POST http://localhost:3000/api/v1/userProfile/createProfile
Content-Type: multipart/form-data
Authorization: Bearer , eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTY5ODM5MTE3NiwiZXhwIjoxNjk4Mzk0Nzc2fQ.oxhk_dXiPwLLyLcHXPKyoSaCqWcDYlcnRcOCutFGuQk

{
"first_name" : "Tisu",
"last_name":"Oke",
"birth_date":"2001-10-02",
"profile_picture":""
}
