POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email": "coba@mail.com",
    "password": "testpassword"
}
###
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email": "coba@mail.com",
    "password": "testpassword"
}

###
POST http://localhost:3000/api/v1/userProfile/createProfile
Content-Type: multipart/form-data
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY5ODM5MTU5NiwiZXhwIjoxNjk4Mzk1MTk2fQ.nXWfXMdgBoRwp_u7y1JXPoWTgHbWEvKUEHXaapN5zek"

{
"first_name" : "Tisu",
"last_name":"Oke",
"birth_date":"2001-10-02",
"profile_picture":""
}
